// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using HexaGen.Runtime;

namespace Hexa.NET.Utilities.Native
{
	public unsafe partial class HexaUtils
	{
		public const int HEXA_UTILS_BUILD_SHARED = 1;

	}
}
