// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using HexaGen.Runtime;

namespace Hexa.NET.Utilities.Native
{
	/// <summary>
	/// <br/>
	/// Allows multiple concurrent readers or a single exclusive writer.<br/>
	/// Writers are given fairness: once a writer is waiting, new readers<br/>
	/// will block until the writer has acquired and released the lock.<br/>
	/// Must be initialized with ReaderWriterLock_Init() before use.<br/>
	/// </summary>
	[StructLayout(LayoutKind.Sequential)]
	public partial struct ReaderWriterLock
	{
		public nuint Storage;

		public unsafe ReaderWriterLock(nuint storage = default)
		{
			Storage = storage;
		}


	}

}
