// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using HexaGen.Runtime;

namespace Hexa.NET.Utilities.Native
{
	public unsafe partial class HexaUtils
	{
		/// <summary>
		/// <br/>
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal static void ReaderWriterLockInitNative(ReaderWriterLock* cLock)
		{
			#if NET5_0_OR_GREATER
			((delegate* unmanaged[Cdecl]<ReaderWriterLock*, void>)funcTable[0])(cLock);
			#else
			((delegate* unmanaged[Cdecl]<nint, void>)funcTable[0])((nint)cLock);
			#endif
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockInit(ReaderWriterLock* cLock)
		{
			ReaderWriterLockInitNative(cLock);
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockInit(ref ReaderWriterLock cLock)
		{
			fixed (ReaderWriterLock* pcLock = &cLock)
			{
				ReaderWriterLockInitNative((ReaderWriterLock*)pcLock);
			}
		}

		/// <summary>
		/// <br/>
		/// Blocks if a writer currently holds or is waiting for the lock.<br/>
		/// <br/>
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal static int ReaderWriterLockLockReadNative(ReaderWriterLock* cLock)
		{
			#if NET5_0_OR_GREATER
			return ((delegate* unmanaged[Cdecl]<ReaderWriterLock*, int>)funcTable[1])(cLock);
			#else
			return (int)((delegate* unmanaged[Cdecl]<nint, int>)funcTable[1])((nint)cLock);
			#endif
		}

		/// <summary>
		/// <br/>
		/// Blocks if a writer currently holds or is waiting for the lock.<br/>
		/// <br/>
		/// </summary>
		public static int ReaderWriterLockLockRead(ReaderWriterLock* cLock)
		{
			int ret = ReaderWriterLockLockReadNative(cLock);
			return ret;
		}

		/// <summary>
		/// <br/>
		/// Blocks if a writer currently holds or is waiting for the lock.<br/>
		/// <br/>
		/// </summary>
		public static int ReaderWriterLockLockRead(ref ReaderWriterLock cLock)
		{
			fixed (ReaderWriterLock* pcLock = &cLock)
			{
				int ret = ReaderWriterLockLockReadNative((ReaderWriterLock*)pcLock);
				return ret;
			}
		}

		/// <summary>
		/// <br/>
		/// <br/>
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal static int ReaderWriterLockTryLockReadNative(ReaderWriterLock* cLock)
		{
			#if NET5_0_OR_GREATER
			return ((delegate* unmanaged[Cdecl]<ReaderWriterLock*, int>)funcTable[2])(cLock);
			#else
			return (int)((delegate* unmanaged[Cdecl]<nint, int>)funcTable[2])((nint)cLock);
			#endif
		}

		/// <summary>
		/// <br/>
		/// <br/>
		/// </summary>
		public static int ReaderWriterLockTryLockRead(ReaderWriterLock* cLock)
		{
			int ret = ReaderWriterLockTryLockReadNative(cLock);
			return ret;
		}

		/// <summary>
		/// <br/>
		/// <br/>
		/// </summary>
		public static int ReaderWriterLockTryLockRead(ref ReaderWriterLock cLock)
		{
			fixed (ReaderWriterLock* pcLock = &cLock)
			{
				int ret = ReaderWriterLockTryLockReadNative((ReaderWriterLock*)pcLock);
				return ret;
			}
		}

		/// <summary>
		/// <br/>
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal static void ReaderWriterLockUnlockReadNative(ReaderWriterLock* cLock)
		{
			#if NET5_0_OR_GREATER
			((delegate* unmanaged[Cdecl]<ReaderWriterLock*, void>)funcTable[3])(cLock);
			#else
			((delegate* unmanaged[Cdecl]<nint, void>)funcTable[3])((nint)cLock);
			#endif
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockUnlockRead(ReaderWriterLock* cLock)
		{
			ReaderWriterLockUnlockReadNative(cLock);
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockUnlockRead(ref ReaderWriterLock cLock)
		{
			fixed (ReaderWriterLock* pcLock = &cLock)
			{
				ReaderWriterLockUnlockReadNative((ReaderWriterLock*)pcLock);
			}
		}

		/// <summary>
		/// <br/>
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal static void ReaderWriterLockLockWriteNative(ReaderWriterLock* cLock)
		{
			#if NET5_0_OR_GREATER
			((delegate* unmanaged[Cdecl]<ReaderWriterLock*, void>)funcTable[4])(cLock);
			#else
			((delegate* unmanaged[Cdecl]<nint, void>)funcTable[4])((nint)cLock);
			#endif
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockLockWrite(ReaderWriterLock* cLock)
		{
			ReaderWriterLockLockWriteNative(cLock);
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockLockWrite(ref ReaderWriterLock cLock)
		{
			fixed (ReaderWriterLock* pcLock = &cLock)
			{
				ReaderWriterLockLockWriteNative((ReaderWriterLock*)pcLock);
			}
		}

		/// <summary>
		/// <br/>
		/// <br/>
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal static int ReaderWriterLockTryLockWriteNative(ReaderWriterLock* cLock, byte preserveWriterFairness)
		{
			#if NET5_0_OR_GREATER
			return ((delegate* unmanaged[Cdecl]<ReaderWriterLock*, byte, int>)funcTable[5])(cLock, preserveWriterFairness);
			#else
			return (int)((delegate* unmanaged[Cdecl]<nint, byte, int>)funcTable[5])((nint)cLock, preserveWriterFairness);
			#endif
		}

		/// <summary>
		/// <br/>
		/// <br/>
		/// </summary>
		public static int ReaderWriterLockTryLockWrite(ReaderWriterLock* cLock, bool preserveWriterFairness)
		{
			int ret = ReaderWriterLockTryLockWriteNative(cLock, preserveWriterFairness ? (byte)1 : (byte)0);
			return ret;
		}

		/// <summary>
		/// <br/>
		/// <br/>
		/// </summary>
		public static int ReaderWriterLockTryLockWrite(ref ReaderWriterLock cLock, bool preserveWriterFairness)
		{
			fixed (ReaderWriterLock* pcLock = &cLock)
			{
				int ret = ReaderWriterLockTryLockWriteNative((ReaderWriterLock*)pcLock, preserveWriterFairness ? (byte)1 : (byte)0);
				return ret;
			}
		}

		/// <summary>
		/// <br/>
		/// </summary>
		[MethodImpl(MethodImplOptions.AggressiveInlining)]
		internal static void ReaderWriterLockUnlockWriteNative(ReaderWriterLock* cLock)
		{
			#if NET5_0_OR_GREATER
			((delegate* unmanaged[Cdecl]<ReaderWriterLock*, void>)funcTable[6])(cLock);
			#else
			((delegate* unmanaged[Cdecl]<nint, void>)funcTable[6])((nint)cLock);
			#endif
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockUnlockWrite(ReaderWriterLock* cLock)
		{
			ReaderWriterLockUnlockWriteNative(cLock);
		}

		/// <summary>
		/// <br/>
		/// </summary>
		public static void ReaderWriterLockUnlockWrite(ref ReaderWriterLock cLock)
		{
			fixed (ReaderWriterLock* pcLock = &cLock)
			{
				ReaderWriterLockUnlockWriteNative((ReaderWriterLock*)pcLock);
			}
		}

	}
}
