// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using HexaGen.Runtime;

namespace Hexa.NET.Utilities.Native
{
	public unsafe partial class HexaUtils
	{
		internal static FunctionTable funcTable;

		/// <summary>
		/// Initializes the function table, automatically called. Do not call manually, only after <see cref="FreeApi"/>.
		/// </summary>
		public static void InitApi()
		{
			funcTable = new FunctionTable(LibraryLoader.LoadLibrary(GetLibraryName, null), 7);
			funcTable.Load(0, "ReaderWriterLock_Init");
			funcTable.Load(1, "ReaderWriterLock_LockRead");
			funcTable.Load(2, "ReaderWriterLock_TryLockRead");
			funcTable.Load(3, "ReaderWriterLock_UnlockRead");
			funcTable.Load(4, "ReaderWriterLock_LockWrite");
			funcTable.Load(5, "ReaderWriterLock_TryLockWrite");
			funcTable.Load(6, "ReaderWriterLock_UnlockWrite");
		}

		public static void FreeApi()
		{
			funcTable.Free();
		}
	}
}
